name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Build (no-default-features)
      run: cargo build --release --no-default-features --verbose
    - name: Build (all-features)
      run: cargo build --release --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
